[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "interbtc-primitives"
version = "1.1.0"

[dependencies]
bstringify = "0.1.2"
serde = { version = "1.0.130", optional = true }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }

# Parachain dependencies
bitcoin = { path = "../crates/bitcoin", default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",

    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",

    "bitcoin/std",
]
