image: "registry.gitlab.com/interlay/containers/rust-base:nightly-2021-03-15"

.only-refs: &only_refs
    only:
        - tags
        - master
        - dev
        - beta
        - rococo
        - web

.rust-base-job:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
    RUSTC_WRAPPER: /usr/local/bin/sccache
  before_script:
    - rustup show
    - rustc --version
    - rustfmt --version
    - cargo --version
    - SCCACHE_START_SERVER=1 SCCACHE_IDLE_TIMEOUT=0 sccache
    - sccache -s

.docker-base-job:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.7.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_HUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --force \
      --build-arg BINARY=${ARTIFACT_BIN_PATH} \
      --context ${CI_PROJECT_DIR} \
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile_release \
      --destination ${DOCKER_REGISTRY_IMAGE}:${ARTIFACT_BIN_PATH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$(date +%s) \
      --destination ${DOCKER_REGISTRY_IMAGE}:${ARTIFACT_BIN_PATH}-${CI_COMMIT_REF_SLUG} \
      --destination ${DOCKER_REGISTRY_IMAGE}:${ARTIFACT_BIN_PATH}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date +%s) \
      --destination ${DOCKER_REGISTRY_IMAGE}:${ARTIFACT_BIN_PATH}-${CI_COMMIT_REF_NAME}
  <<: *only_refs

stages:
  - test
  - build
  - publish
  - release

test:
  stage: test
  extends:
    - .rust-base-job
  script:
    - cargo fmt -- --check
    - cargo check --workspace --release
    - cargo test --workspace --release --features runtime-benchmarks

build-standalone:
  stage: build
  extends:
    - .rust-base-job
  variables:
    ARTIFACT_BIN_PATH: interbtc-standalone
  script:
    - find ./ -name Cargo.toml -exec ./scripts/update_cargo_version.sh {} \;
    - cargo build --release --bin interbtc-standalone
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}-standalone"
    paths:
      - target/release/${ARTIFACT_BIN_PATH}

build-parachain:
  stage: build
  extends:
    - .rust-base-job
  variables:
    ARTIFACT_BIN_PATH: interbtc-parachain
  script:
    - find ./ -name Cargo.toml -exec ./scripts/update_cargo_version.sh {} \;
    - cargo build --release --bin interbtc-parachain
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}-parachain"
    paths:
      - target/release/${ARTIFACT_BIN_PATH}

docker-publish-standalone:
  dependencies:
    - build-standalone
  variables:
    ARTIFACT_BIN_PATH: interbtc-standalone
    DOCKER_REGISTRY_IMAGE: interlayhq/interbtc
  extends:
    - .docker-base-job

docker-publish-parachain:
  dependencies:
    - build-parachain
  variables:
    ARTIFACT_BIN_PATH: interbtc-parachain
    DOCKER_REGISTRY_IMAGE: interlayhq/interbtc
  extends:
    - .docker-base-job

